INFO     HTTP_CLIENT:event_hooks.py:27 Make POST request to http://localhost:8000/api/v1/users
INFO     HTTP_CLIENT:event_hooks.py:37 Got response 200 OK from http://localhost:8000/api/v1/users
INFO     HTTP_CLIENT:event_hooks.py:27 Make POST request to http://localhost:8000/api/v1/authentication/login
INFO     HTTP_CLIENT:event_hooks.py:37 Got response 200 OK from http://localhost:8000/api/v1/authentication/login
INFO     HTTP_CLIENT:event_hooks.py:27 Make GET request to http://localhost:8000/api/v1/files/incorrect-file-id
INFO     HTTP_CLIENT:event_hooks.py:37 Got response 422 Unprocessable Entity from http://localhost:8000/api/v1/files/incorrect-file-id
INFO     BASE_ASSERTIONS:base.py:16 Check that response status code equals to 422
INFO     FILES_ASSERTIONS:files.py:125 Check get file with incorrect file id response
INFO     ERRORS_ASSERTIONS:errors.py:38 Check validation error response
INFO     BASE_ASSERTIONS:base.py:64 Check that length of "details" equals to 1
INFO     ERRORS_ASSERTIONS:errors.py:17 Check validation error
INFO     BASE_ASSERTIONS:base.py:32 Check that "type" equals to uuid_parsing
INFO     BASE_ASSERTIONS:base.py:32 Check that "input" equals to incorrect-file-id
INFO     BASE_ASSERTIONS:base.py:32 Check that "context" equals to {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `i` at 1'}
INFO     BASE_ASSERTIONS:base.py:32 Check that "message" equals to Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `i` at 1
INFO     BASE_ASSERTIONS:base.py:32 Check that "location" equals to ['path', 'file_id']
INFO     SCHEMA_ASSERTIONS:schema.py:19 Validating JSON schema